name: v0.0.0_basic_rainbow
env: basic_env
model: basic_model
run: DQN
stop:
    training_iteration: 100
    #timesteps_total: 1000000
    #episode_reward_mean: 200
config:
    # overall
    framework: torch
    #num_gpus: 0.2
    #num_workers: 8
    # double q
    double_q: false
    # dueling
    dueling: false
    hiddens: [512]
    # distributional dqn
    num_atoms: 1
    v_min: -10
    v_max: 10
    # noisy
    noisy: false
    sigma0: 0.5
    # n-step bootstrap
    n_step: 1
    # prioritized
    buffer_size: 100000
    prioritized_replay: false
    prioritized_replay_eps: 0.5
    prioritized_replay_alpha: 0.5
    prioritized_replay_beta: 0.5
    final_prioritized_replay_beta: 1.0
    prioritized_replay_beta_annealing_timesteps: 2000000
    # training
    target_network_update_freq: 8000
    lr: .0000625
    gamma: 0.99
    adam_epsilon: .00015
    learning_starts: 20000
    rollout_fragment_length: 4
    train_batch_size: 32
    timesteps_per_iteration: 10000
    exploration_config:
      epsilon_timesteps: 200000
      final_epsilon: 0.01